# https://taskfile.dev

version: "3"

vars:
  PROJECT: lametric

tasks:
  default:
    cmds:
      - poetry run python -m app
    silent: true

  logs:
    desc: monitor logs
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;journalctl --user -u {{.PROJECT}} -f' | ccze -A

  start:
    desc: start the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user start {{.PROJECT}}'

  restart:
    desc: restart the service
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user restart {{.PROJECT}}'

  stop:
    desc: stop the server
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user stop {{.PROJECT}}'

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push  || true

  pull:
    desc: pulls from git
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd ~/{{.PROJECT}};git reset --hard;git pull'

  pp:
    desc: push and pull
    cmds:
      - task: push
      - task: pull

  install:
    desc: calls poetry install and npm ci
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd ~/{{.PROJECT}};poetry install'

  deploy:
    desc: shortcut for stop -> push -> pull -> restart
    cmds:
      - task: stop
      - task: push
      - task: pull
      - task: install
      - task: restart

  systemd-exec:
    desc: run the server
    cmds:
      - direnv exec . poetry run python -m app
